name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: "Ruby ${{ matrix.ruby }}, omniauth ${{ matrix.omniauth }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.0"
            omniauth: "~> 2.0"
          - ruby: "2.7"
            omniauth: "~> 2.0"
          - ruby: "2.7"
            omniauth: "~> 1.4"
          - ruby: "2.6"
            omniauth: "~> 1.4"
          - ruby: "2.5"
            omniauth: "~> 1.4"
          - ruby: "2.4"
            omniauth: "~> 1.4"
          - ruby: "2.3"
            omniauth: "~> 1.4"
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        CI: true
        OMNIAUTH_VERSION: "${{ matrix.omniauth }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
            bundle-${{ matrix.ruby }}-
      - name: Upgrade Bundler to 2.0 (for older Rubies)
        run: gem install bundler -v '~> 2.0'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          bundle update
      - name: Run Rubocop
        run: bundle exec rubocop
      - name: Run RSpec
        run: bundle exec rspec
